// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get():Promise<string>;

export function ScreenShot():Promise<string>;

export function Storage(arg1:string):Promise<number>;

export function Totp(arg1:string):Promise<string>;
