// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Get():Promise<string>;

export function ScreenShot():Promise<string>;

export function Totp(arg1:string):Promise<main.TotpRes>;
