// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['main']['App']['Get']();
}

export function ScreenShot() {
  return window['go']['main']['App']['ScreenShot']();
}

export function Storage(arg1) {
  return window['go']['main']['App']['Storage'](arg1);
}

export function Totp(arg1) {
  return window['go']['main']['App']['Totp'](arg1);
}
